on:
    workflow_dispatch:
        inputs:
            release-tag:
                type: string
                required: true

env:
    GH_TOKEN: ${{ github.token }}

jobs:
    my-nice-job:
        runs-on: ubuntu-latest
        steps:
            - run: gh release create ${{ inputs.release-tag }}

        