name: Workflow

on:
  push:

jobs:
  first-job:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - id: first-step
        name: First step
        uses: actions/checkout@v4
        with:
          repository: domix24/studious-fishstick
          path: first
      - id: second-step
        name: Second step
        uses: actions/checkout@v4
        with:
          path: second
      - id: merge-repositories
        name: Merge repositories
        shell: bash
        run: |
          cd first
          git branch new-branch
          git checkout new-branch
          rm -rf ../second/.git
          cp -r ../second .
          git add .
          git commit -m "abc-123"
          git push origin new-branch
      - id: show-data
        name: Show data
        shell: bash
        run: |
          ls -la first
          cd first && git status
          cd .. && ls -la second
          cd second && git status