name: Workflow

on:
  push:

jobs:
  first-job:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - id: first-step
        name: First step
        uses: actions/checkout@v4
        with:
          repository: domix24/studious-fishstick
          path: first
      - id: show-data
        name: Show data
        shell: bash
        run: |
          ls -la first
          git status