name: Workflow

on:
  push:

jobs:
  first-job:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - id: first-step
        name: First step
        uses: actions/checkout@v4
        with:
          repository: domix24/studious-fishstick
          path: first
      - id: second-step
        name: Second step
        uses: actions/checkout@v4
        with:
          path: second
      - id: merge-repositories
        name: Merge repositories
        shell: bash
        run: |
          cd first
          git branch new-branch
          git checkout new-branch
          rm -rf ../second/.git
          cp -r ../second .

          git config user.email "domix24@users.noreply.github.com"
          git config user.name "domix24"
          git config commit.gpgsign true
          git config user.signingkey ${{ secrets.COMMIT_SIGNING_KEY }}

          echo -n "${{ secrets.GPG_PUBLIC_KEY }}" | base64 --decode | gpg --import
          echo "--sep0--"
          echo -n "${{ secrets.GPG_PRIVATE_KEY }}" | base64 --decode | gpg --import
          echo "--sep1--"

          # gpg --list-keys
          # git add .
          # git commit -m "abc-123"
          # 
          # git log --show-signature
      - id: show-data
        name: Show data
        shell: bash
        run: |
          ls -la first
          cd first && git status
          cd .. && ls -la second
          cd second && git status